import os
import requests
from typing import Any

class GeminiClient:
    """Real Gemini integration using REST API."""
    
    def __init__(self, api_key: str | None = None, model: str = "gemini-2.0-flash"):
        self.api_key = api_key or os.getenv("GEMINI_API_KEY", "")
        self.model = model
        self.base_url = "https://generativelanguage.googleapis.com/v1beta/models"
    
    def generate_sow_text(self, prompt: str) -> str:
        """Generate SOW text using real Gemini API."""
        if not self.api_key:
            return "SOW Draft (No API Key):\n\n" + prompt[:1000]
        
        try:
            url = f"{self.base_url}/{self.model}:generateContent"
            headers = {
                "Content-Type": "application/json",
                "X-goog-api-key": self.api_key
            }
            
            enhanced_prompt = f"""
Generate a professional Statement of Work document based on the following information:

{prompt}

Please create a comprehensive SOW with:
1. Executive Summary
2. Project Scope and Objectives
3. Detailed Services Description
4. Deliverables and Acceptance Criteria
5. Timeline and Milestones
6. Resource Allocation
7. Budget and Payment Terms
8. Terms and Conditions

Format it professionally with clear sections and bullet points where appropriate.
"""
            
            payload = {
                "contents": [
                    {
                        "parts": [
                            {
                                "text": enhanced_prompt
                            }
                        ]
                    }
                ]
            }
            
            response = requests.post(url, headers=headers, json=payload, timeout=30)
            
            if response.status_code == 200:
                result = response.json()
                if "candidates" in result and len(result["candidates"]) > 0:
                    content = result["candidates"][0]["content"]["parts"][0]["text"]
                    return f"Professional SOW Generated by Gemini AI:\n\n{content}"
                else:
                    return f"SOW Draft (API Response Issue):\n\n{prompt[:1000]}"
            else:
                print(f"Gemini API Error: {response.status_code} - {response.text}")
                return f"SOW Draft (API Error {response.status_code}):\n\n{prompt[:1000]}"
                
        except Exception as e:
            print(f"Gemini API Exception: {e}")
            return f"SOW Draft (Exception: {str(e)}):\n\n{prompt[:1000]}"